public class OrderDealsExtension {
	
	//public List<PostingRides__c> deals {get;set;}
	//public String dealId {get;set;}
    //public OrderDealsExtension() {
	//	loadData();
	//}
		
//	public void loadData() {
			
//		deals= [select Name__c,AvailableSeats__c,DateTime__c,CarModel__c,From__c,To__c from PostingRides__c];
//	}
//	public void deleteDeal(){
  //     deals = [Select id,Name__c,AvailableSeats__c,DateTime__c,CarModel__c,From__c,To__c from PostingRides__c where id =:dealId];
    //  if(deals.size()> 0 || deals[0].Id!= ''){
      //delete deals;
      //}
      //loadData();
  
 //  }	
}